version: '2'

services:

    # Database service
    DATA_Postgres:
        image: postgres
        container_name: DATA_Postgres
        environment:
            POSTGRES_USER: "lambda"
            POSTGRES_PASSWORD: "lambda_password"
            POSTGRES_DB: "lambda_db"
        volumes:
            - DATA_TIER_DATA:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    DATA_TIER_DATA: